name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: pnpm install
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: pnpm run shipit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
